### ISSUE TITLE
The thermostat does not set the temperature

### ISSUE THREAD

**Issue by mkania11** [MassiPi/maxcube#2]
The thermostat does not set the temperature:

Logger: custom_components.maxcube.maxcube.commander
Source: custom_components/maxcube/maxcube/commander.py:85
Integration: eQ-3 MAX!
First occurred: 18:58:32 (10 occurrences)
Last logged: 19:46:49

Error sending radio message to Max! Cube: Deadline send-radio-msg[0/2]:cmd-reply[0/2]
Changing the temperature from the MAXCUBE app works fine.

What could be the cause?

Marcin Kania

**Comment by MassiPi** [comment]
> Error sending radio message to Max! Cube: Deadline send-radio-msg[0/2]:cmd-reply[0/2]

this is an error in the connection to the cube / sending message, there's not much i can tell you..

**Comment by mkania11** [comment]
The scheme looks like this:

1. I set the temperature on the MaxCube Home Assinstant thermostat (climate.xxx)
2 I get Deadline send-radio-msg[0/2]:cmd-reply[0/2] error.
3. the thermostat reads the temperature from the head, the Home Assistant thermostat "goes back" to the previously set temperature
4. set the temperature again in HA
5. the gateway restarts

As long as I do not set the temperature (just read the values) - the gateway works stably and nothing happens.
Max Home Automation works normally, the gateway does not restart. But maybe the temperature setting in HA is to blame?

**Comment by MassiPi** [comment]
i'd try resetting the cube _and all the devices_
If you look on HA community, this has solved more than one strange issue.
What do you mean with "the temperature setting in HA is to blame"? it uses the protocol used also by the MAX local application (you can check sniffing commands with wireshark, tcpdump or something like that)
Also, how did you set up the "update interval" in HA config? there is a "fake" sleep in the integration to get an update as soon as a new command is sent to the cube, maybe you have a longer update interval? (i use 1 second as update interval)

**Comment by mkania11** [comment]
Thank you for your interest. I think not many people are using this system yet, but it's still quite decent. And quieter compared to Chinese ZIGBEE heads.
My setting is "scan_interval: 300."

I will try to reset the cube. From my observations, it seems that after some time from restarting the cube (1 to several hours), the situation returns to normal, the cube does not reset, and the thermostats are updated. Cube reset can be triggered right after turning it on and sending a temperature setting command to the thermostats from the Home Assistant plug-in. Setting the temperature in the same way through MAX! Home Automation (http://www.dmitry-kazakov.de/ada/max_home_automation.htm) does not cause the cube to reset. Hence, my question and doubts.

But still, thank you very much for giving wings to the old system that was supposed to be discarded after the season. Now, it has received a second life.

**Comment by MassiPi** [comment]
with my code the connection to the cube is forced to persistent, so don't worry putting the scan interval to a very low value (really, try with 1!)
just to understand if this can be the reason for your error (never seen), maybe the short timeout with a interval that long is giving errors. Probably i should disable the scan interval totally..
And most of all, i've never seen the cube resetting for a command! (for this reason i'd try hardly resetting it AND ALL DEVICES)

Sorry, i understood you were using the official max local app, not this custom one. I remember this, i tried using it some years ago and it broke my whole setup so i'm not a big fan :)

**Comment by mkania11** [comment]
Thank you for your response. I'm trying with setting 1, and I will continue to observe HA's behavior.
