### ISSUE TITLE
Warning in home assistant 2024.10 - Entity None

### ISSUE THREAD

**Issue by alegiovannelli** [MassiPi/maxcube#3]
In Home Assistant Logs I have the next warning:

`[homeassistant.components.climate] Entity None (<class 'custom_components.maxcube.climate.MaxCubeClimate'>) implements HVACMode(s): off, auto, heat and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please report it to the author of the 'maxcube' custom integration`

Thank you for support.

**Comment by MassiPi** [comment]
hello, are you sure you are using the last version of the code? i think i can remember i fixed it a lot of time ago and i do not see any worning in logs :)

(oh, damn, maybe i did not upload the right code, let me check this evening..)

**Comment by alegiovannelli** [comment]
I downloaded the code from the repository last 16 september.
I think is the latest one. 
Thanks if you check your code and commits.

**Comment by MassiPi** [comment]
damn i forgot the fix :)
try please with the updated file..

**Comment by alegiovannelli** [comment]
Thanks, now, after updating the component, I no longer find the error in the logs. Thanks again.

**Comment by MassiPi** [comment]
that was my fault, sorry :)
ciao Alessandro!

**Comment by ovancantfort** [comment]
Just wanted to leave a little thank you note for your work on adapting and maintaining this.
I simply would hate to throw a working setup because of a decision of planned obsolescence.
Have a nice end of year !

**Comment by MassiPi** [comment]
nice to see someone else still using this :)

**Comment by alegiovannelli** [comment]
I also use this integration. The hardware still works fine, it's a shame can't use it anymore. Thanks to this project it has been given new life. Thank you again!
